Documentation for Ionic
couchbaselabs/cbl-ionic-docs pull request #1
Opened 2024-04-01 17:24 UTC by azaddhirajkumar

2024-04-01 18:11 UTC, biozal requested changes

2024-04-01 18:11 UTC, biozal commented on docs/databases.md
> +**Example: Initializing Capacitor Engine and Database Context**
the Database Context is a react thing that doesn't come the framework.  It's a pattern like Services.  So we would need to switch this out to really state they just need to make the engine and keep track of it using something like the Provider/Context or Service pattern for the life of the application running.  Most developers should know what that means.

2024-04-01 18:11 UTC, biozal commented on docs/databases.md
> +import { useContext } from 'react';
we never want to include page code, it will alienate developers using something other than React.  We need to just specifically show the actual code it takes to make the database encryption work, which is just a setting in the Database Config.

2024-04-01 18:11 UTC, biozal commented on docs/databases.md
> +
We should also mention the Jetbrains Plugin for Jetbrains based IDEs like Webstorm, Idea, Android Studio, etc.  That would be a good promotion for the work Denis and the other team members are doing.

2024-04-02 06:00 UTC, azaddhirajkumar commented on docs/databases.md
> +**Example: Initializing Capacitor Engine and Database Context**
Done

2024-04-02 06:40 UTC, azaddhirajkumar commented on docs/databases.md
> +
Done

2024-04-23 16:02 UTC, biozal approved these changes

2024-04-23 16:02 UTC, merged